### PR TITLE
RTU remake + minor fixes

### LINKED ISSUE #15: 5.5 Reports on all tag values by id

### PR DESCRIPTION
**Pull request by magley**
Closes #15 #16 and #23

#23 : If a tag value goes below its min or max, it gets clamped.

#15 : I've created the `ReportManager` project and inside a single type of report: enter the ID of a tag, and it spits out all recorded values for that tag. The old values are saved as `TagLog` objects on the server.

#16 : Completely rewritten the RTU code (the idea is more or less the same), created a new schematic (20-30ish measures) and hooked it up on the db context bootup. It's not perfect: I would have to write a graph traversal to truly connect everything, but for the sake of this project it's "connected enough" - we didn't even have to do this in the first place, our RTU could've been just a bunch of independent random variables.

My advice is not to go too deep into the RTU code now. As for the configuration and loading everything from a text file, the only thing you need is `SimulatorNew`'s ctor and the db context initialization. It'll be more of a chore than anything else.

### CODE REVIEW

File: USca/USca-Server/Tags/TagWorker.cs [hunk 1]
```diff
@@ -118,10 +124,32 @@ private void UpdateTag()
...
+                            tag.Value = measure.Value;
+                            Tag.Value = measure.Value; // Do we need this?
+                            db.SaveChanges();
+                        }
+                    }
+                }
+
+                // Log the new value.
+                _tagLogService.AddFrom(Tag, measure.Timestamp);
+            }
```
Comment (elkcert) [inline USca/USca-Server/Tags/TagWorker.cs:151]: Is this necessary? Technically only input tags have a value, so for output tags we only need to add a `TagLog`, and not also update the `Tag` itself, neither the thread's local `Tag` nor the one we retrieve from and persist to the database.
Aside from the business logic concern, since this PR we are making a considerably larger number of database operations (my HDD is constantly churning). It's probably a good time to start looking at optimizations. Aside from this change, two general ones come to mind:
- Use in-memory databse
- Don't store `Measures` in database, but perhaps in a `Dictionary` in `TagWorker`? Writing a new `Measure` every 100ms (that's how often the RTU updates the readings now) to the database is expensive.

File: USca/USca_RTU/Data/schema.png
Comment (elkcert) [inline USca/USca_RTU/Data/schema.png:1]: Add label for the sun symbol (temperature?)

File: USca/USca_RTU/Processor/Simulator/SimTank.cs [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+using System.Threading.Tasks;
+
+namespace USca_RTU.Processor.Simulator
+{
+    public partial class SimTank : INotifyPropertyChanged
+    {
+        public int Address { get; set; }
+        public string Name { get; set; } = "";
+        private double _value;
+        public double Value { get { return _value; } set { _value = Math.Max(0, value); } }
```
Comment (elkcert) [inline USca/USca_RTU/Processor/Simulator/SimTank.cs:15]: This is the only simulated object where we do value clamping, and without a max value at that. Is this deliberate?

File: USca/USca_RTU/Processor/SimulatorNew.cs [hunk 3]
```diff
@@ -0,0 +1,237 @@
...
+            HeatSources.Add(CoolingTankStartingTemp);
+
+            ThermometerBindings.Add(CoolingTankThermometer_Binding);
+
+            Manometers.Add(Manometer);
+            Compressors.Add(Compressor);
+            PressureBindings.Add(PressureBinding);
+        }
+
+        public void PertubateRates()
```
Comment (elkcert) [inline USca/USca_RTU/Processor/SimulatorNew.cs:141]: PertubateRates -> PerturbateRates

File: USca/USca_RTU/Processor/SimulatorNew.cs [hunk 4]
```diff
@@ -0,0 +1,237 @@
...
+using System.ComponentModel;
+using USca_RTU.Processor.Simulator;
+using USca_Server.Tags;
+
+namespace USca_RTU.Processor
+{
+    public partial class SimulatorNew : INotifyPropertyChanged
+    {
+        private int AddressCnt = 0;
+        private Random r = new();
```
Comment (elkcert) [inline USca/USca_RTU/Processor/SimulatorNew.cs:12]: Should provide a seed so we have repeatable simulations

File: USca/USca_ReportManager/Controls/ReportByTagId.xaml.cs [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+                {
+                    TagLogs.Add(o);
+                }
+                TagName = res.TagName;
+            }
+            catch (NotFoundException)
+            {
+                MessageBox.Show("Tag not found!", "Failure", MessageBoxButton.OK);
+                TagLogs.Clear();
+                TagName = "";
```
Comment (elkcert) [inline USca/USca_ReportManager/Controls/ReportByTagId.xaml.cs:43]: First clear `TagLogs` and `TagName`, then display the message. Alternatively only show the message box without clearing old values, maybe replacing `TxtTagId.Text` with previous valid id? Doesn't really matter anyways.

**Review by elkcert — CHANGES_REQUESTED** [review]

File: USca/USca_RTU/Data/schema.png
Comment (elkcert) [reply USca/USca_RTU/Data/schema.png:1]: Also, in the actual RTU window the value labels are slightly cropped on the right side. Does this also happen to you?

File: USca/USca-Server/Tags/TagWorker.cs (hunk 1 above)
Comment (magley) [reply USca/USca-Server/Tags/TagWorker.cs]: The two methods below, `SendData` and `CheckAlarms`, use `Tag.Value`, which needs to be clamped. In other words, measure value != tag value. On the other hand, you're right that we don't actually have to save it to the database, since the `Tag` object is shared within the `TagThreadWrapper`, so the code can be simplified.

As for the first bullet point, we should consider _not_ erasing the database on every run. 

As for the second one: the RTU updates the readings every 100ms, but the data itself is sent every 250ms. Also it's written in a batch so it's 1 `SaveChanges` every 250ms. If you want to increase the period between two writes, go ahead.
I don't think that's a big cost on the I/O. It's the TagLogs that are problematic, because it's 1 I/O per tag, which is 4*N individual writes per second. I've batched the writes.

[2ae9460](https://github.com/magley/untitled-scada-project/pull/25/commits/2ae9460cf2ee20ad0a53e9f35a986c2f1d4efb8c)

File: USca/USca_RTU/Data/schema.png
Comment (magley) [reply USca/USca_RTU/Data/schema.png:1]: [e0cf9df](https://github.com/magley/untitled-scada-project/pull/25/commits/e0cf9df36bf78cc3d9f03834cfb2d2eb7f1a925b)

There's no cropping on my computer:

image

File: USca/USca_RTU/Processor/Simulator/SimTank.cs (hunk 2 above)
Comment (magley) [reply USca/USca_RTU/Processor/Simulator/SimTank.cs:15]: It doesn't make sense for a tank to have negative amount of something. It's either empty or has something in it. There's no upper boundary because then I would also have to simulate "spilling" and giving the tank a maximum capacity. It's too much work. We have alarms, that's enough.

File: USca/USca_RTU/Processor/SimulatorNew.cs (hunk 3 above)
Comment (magley) [reply USca/USca_RTU/Processor/SimulatorNew.cs]: [cb8f846](https://github.com/magley/untitled-scada-project/pull/25/commits/cb8f846e169619bd8996044595ab4f90a191df9a)

File: USca/USca_RTU/Processor/SimulatorNew.cs (hunk 4 above)
Comment (magley) [reply USca/USca_RTU/Processor/SimulatorNew.cs]: [abf71c9](https://github.com/magley/untitled-scada-project/pull/25/commits/abf71c91abba5eb5614b158977afb88948a1e6c3)

File: USca/USca_RTU/Data/schema.png
Comment (elkcert) [reply USca/USca_RTU/Data/schema.png:1]: On closer inspection what looked like a cropped digit was actually the litre symbol...

File: USca/USca_ReportManager/Controls/ReportByTagId.xaml.cs (hunk 5 above)
Comment (magley) [reply USca/USca_ReportManager/Controls/ReportByTagId.xaml.cs]: I did the first thing (swap order).
[89d2b85](https://github.com/magley/untitled-scada-project/pull/25/commits/89d2b8527281fc24569a356bb773d5c77aca992d)

File: USca/USca_RTU/Data/schema.png
Comment (magley) [reply USca/USca_RTU/Data/schema.png:1]: Ah yes, it looks a bit blocky, but I felt like a regular `l` would look too similar to a `1`.

File: USca/USca_RTU/Processor/SimulatorNew.cs (hunk 4 above)
Comment (elkcert) [reply USca/USca_RTU/Processor/SimulatorNew.cs]: This doesn't compile, make `Seed` const

Comment (magley) [reply USca/USca_RTU/Processor/SimulatorNew.cs]: I've made it `static` in case we ever want to (de)serialize the seed from a config.

[9baad77](https://github.com/magley/untitled-scada-project/pull/25/commits/9baad77e0df80c3f0efdca99a6c19f9d6c43c86f)

**Review by elkcert — APPROVED** [review]
